language: node_js
node_js:
- '0.12'
before_install:
- npm install -g grunt-cli
- npm install -g bower
install:
- npm install
- bower install
before_script:
- python -m SimpleHTTPServer &
- sleep 2
env:
  global:
  - secure: 3xFKU/ko37ZSahKUWhb5BAKZSWlVNP56FhIxdDQy2MOetjcE04xQYvhC2qrzAn2BQJkvyvzqJTC26sMUNh/QDVBslJgW9lb9K6G10tdO0z3YTNF1hnDYpkv/MNP6qt4oNETIcuUYu4oXwzacQLPZ5OUZTw5UOo+pX7FnUp3wcYib2hjafIYOGCZrDF+L0+T1VwGRaZoGVtTSSESURYuyX7VGqck3oU5Ys5PgQkTIJD/bfvEnA4q08qd0S4rk64IWicvhMpawp0Qv8VBUnT95ETAcwtad3cxqI6VlpvBU8r5VjgHOYFEbqSc7j8eQIXPRqsKQ1enENFah8UXAKl3i02XQbAdcWMIwTqAA8nsKB+GtEnJjtFbTsmNYRkf8o5KYgd7VXDsPEp3yTvzA/IaS3mx43Rdiw3Dl2L0oQmaPJHFmjRs9lZt25KUwOtFJ0fos8lF4UZAZq18BJlGvkLD00AFte2F2Ohi8BZsbQ3H3IgliwyXKyNcr44sgvNnY71Z6JUg8nUwQi81etRvqfRt0kBFJEMc9IWdVF6yhsRPqTN2Bzrj3bIG107Uw+LNXoknSc7ND6gwdYEdNaDubqYk3dMTphehS/5LUdefKLffEWKwzGKI4Y1crxpZSDK+4Q+gg6+twYjq+Nsgw5gvJQvThBZEoQT/QH9QO+eSEgqis/JM=
  - secure: 4oez8PSze0FVCVWhkgBm6yqEfSbBueJBJygoAd6+5RrlqFsvqYpLDhmPsAW5z6ksA61mDnBTLHbt2wgfm9bWkYqlAKXsEIoK6FJGUzd3uTv38Hgyda8y21WA/qWxVXUqd8DlCk10s29HvlTJmZkM4Sblg8pCyliaJi+z8pNeNUzxJqZGAXDZYHwasR0XdHp0+in4RsxRraMFs36cXzs0ce9/Ba3XXH8a/oj+YgCXShS4VZRqXdeszGz1HQHfVbG7xKQBBO5Q9fnRhI5ujxE3RfCZwqX4+Ygx7f5rBst95KA3A9qoA+DHGJpN/wzXGLt7ocz3coBI1DC643cSsUVULpSIo3D49CetqFhlWLJ+g6o39X7XlC2Hfo40913q5NXFkOz0R4Ukwtw1djMcEW3GM4Z75X/2KwUgmRRLYSP61YN6BytoifWRR36AQavnNBx6KzNFqQH5kFqhj8wwfY9qbcjnp0jJN6LxGbQHcE4x7bl0AZlphVXA8cPhUON0oNeR+1uwidcu7cNjKgGznq+ewYvUtl1MsTiCEPkZF0CDU9Qhec0n6lurjlgR3qcqlZgQg9e8NO30LYDbYwxmPa84Wf6qY47ddJ/Yr1fj+oRNgxEKwKHHL6aEFJSt4PvymW4DaRU9FKBoFizsy9xUy/NnddoHiDkFYgKAXUdP5GcD/UI=
addons:
  sauce_connect: true
notifications:
  slack:
    secure: moKn6T0CD+9WtV9o437lpQI8C2rXMpcRPVs3JKQUFsvIlek9LZxB9hrSHHn95Tls2LcNT4hs4JPXBqTwqLKVrhIxYnuAFkIqM8qv0XbxTh4nH+6xpGDSLrhLh9J1MVpElSv5zST5+iYDYYdlR3gMr9tAgcuvFoJjH80CZJR6KmBIVsSwllgvcA2cSxzPQzKVJL+DUYblM7xSk7K4/l2BBGPKlv3W2lOGdyGogImaVHh9jU73Vv5Tc02r3dQpiPZi5wv/0G/J/flUEOZEouHyzgUa7kF0m5NN7ZOOd08N+9jaWJI8Ne3l6YM/HdWShXJ4hITCCnfbEkqlhg8H/0LYsOx//e5Q4Ck1lrMSV0o9xDUT0cu0BsAbKIcRH5OLNMeJ4Qeg5yS1I8WeN1xdKkaib5Qf3XshThHeFMVPclR9833Ov8DnkEE8D98i1H8pyz4tqv22P+YkILZR+Ju0tqOOmg34aabLS2eKCX+b7znfiLJQ2A0rHiDUun+f8HqaS1LPLQ7lqv4TcraYcWTodL/1LVsN+SpF4Q07DjlgelYeqI5FYRHuV5acsCG9etoOM5Dxc49xhG3HY2EH/L4CcXuoW4aZkzt13eEegZi1ROM39H+n0GQX37du8ztAqH+hOknAhWEVStDp6vjufxUJU0DKUnXS5DZkCpPHk4oBX1dojf0=
